# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abe Makes Things
email: abe@wrkhrs.co
description: Some information about Abe Garcia
favicon:     "/favicon.ico"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thehonestape.com" # the base hostname & protocol for your site
github_username:  thehonestape
port: 8888


# Build settings
markdown: kramdown
